### PR TITLE
fix: use prefixed formats and new design

### LINKED ISSUE #28: Format filtrering mangler innhold
Filteret for formater i Datafabrikken mangler innhold

### PR DESCRIPTION
**Pull request by jeffreiffers**
Fixes #28

### CODE REVIEW

File: src/entrypoints/main/router/pages/datasets-page/components/filters/index.tsx [hunk 1]
```diff
@@ -1,31 +1,142 @@
...
+      item.label =
+        label || `${translationsService.translate('formatType.UNKNOWN')}`;
+      results[group] = results[group] || [];
+      results[group].push(item);
+      return results;
+    }, {});
+  };
+
+  // eslint-disable-next-line no-console
+  console.log({ formatParameter });
```
Comment (oyvindis) [inline src/entrypoints/main/router/pages/datasets-page/components/filters/index.tsx:85]: Fjerne denne
